services:
  - type: web
    name: reybraztech-scraper
    env: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install --include=dev && rm -rf /opt/render/.cache/puppeteer && npx puppeteer browsers install chrome && echo "Chrome installed:" && ls /opt/render/.cache/puppeteer && rm -rf dist && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
